### ISSUE TITLE
hdiutil internet-enable

### ISSUE THREAD

**Issue by rsyncOSX** [create-dmg/create-dmg#76]
macOS Catalina - 

"hdiutil internet-enable" is deprecated

**Comment by aonez** [comment]
Thanks for the tip @rsyncOSX. I expected to see a deprecation warning but the option is fully gone.

**Comment by aonez** [comment]
I'm reopening this because this feature should be disabled in Catalina ;)

**Comment by mRs-** [comment]
Is there a solution yet to fix this?

**Comment by mRs-** [comment]
Yeah that's a good idea, currently I'm using the homebrew version, maybe I should change this to self Distribution :)

**Comment by aonez** [comment]
I though this was an optional feature. So it fails on Catalina if you don’t set the “nointernet” option?

**Comment by aonez** [comment]
That should do it: https://github.com/andreyvit/create-dmg/commit/737d2d6d0eab04a10876238869eeaf5821ac7f8d

I'll be pushing to brew this night or tomorrow.

**Comment by mRs-** [comment]
awesome!

**Comment by rsyncOSX** [comment]
I am closing this issue now, it is solved...

**Comment by aonez** [comment]
I'm having a bit of trouble pushing the brew update, but eventually it will work...

https://github.com/Homebrew/homebrew-core/pull/45310

**Comment by jakob** [comment]
@aonez it doesn't look like your commit actually fixed it. On macOS 10.15 Catalina, the check just causes the script to abort and return a non-zero exit code (because of the -e flag)

I've tried to fix your check and submitted PR #79

**Comment by aonez** [comment]
@jakob already merged but in my tests the old code also works. You mean the `-eq` comparison?

**Comment by jakob** [comment]
@aonez `hdiutil internet-enable -help` returns a non-zero exit code in catalina. Your code contained the following line:

```bash
INTERNET_ENABLE_CHECK="$(hdiutil internet-enable -help 2>&1)"
```

This line caused the whole script to exit with a non-zero exit code (since the script sets the `-e` flag at the very top)

The `if [ $? -eq 0 ]` line was never even reached.

This didn't really matter if you called the script directly, since it didn't do anything afterwards except print a message.

But if you called create-dmg from a different script, that script would think that create-dmg failed because it returned a non-zero exit code.

I fixed it by just checking the exit code from `hdiutil internet-enable -help` directly in an if statement. If statements explicitely check for non-zero exit codes, so the exit code on Catalina doesn't cause the script to abort.

**Comment by mRs-** [comment]
That's exactly what I need. Does that already exist on homebrew? I am using create-dmg in my script and it's currently failing.

**Comment by aonez** [comment]
@mRs- sadly the current build does not pass brew tests. Any help here is welcome: https://github.com/andreyvit/create-dmg/issues/76#issuecomment-541765642

**Comment by mRs-** [comment]
It seems that the problem is caused by the new security settings of Catalina. It might be enough to add the script on the test machines. If there is a CLI for it is not known to me :/

**Comment by apjanke** [comment]
I think this is fixed now. There [is now a check to see if `hdiutil internet-enable` works](https://github.com/create-dmg/create-dmg/blob/edbad473d513c6d71b516fa87c0717618a99326f/create-dmg#L423-L434), and I've (clumsily) cleaned up the sandboxing stuff so that `brew test` now passes on Mojave and later. create-dmg 1.0.8 [has been accepted by Homebrew core](https://github.com/Homebrew/homebrew-core/pull/55413).

Please re-open if you're still encountering problems.

**Comment by mightybyte** [comment]
I'm still encountering problems with this.  Here's the last bit of output:

```
Elapsed Time:  6.544s
File size: 33930770 bytes, Checksum: CRC32 $613F58DF
Sectors processed: 266320, 211356 compressed
Speed: 15.8Mbytes/sec
Savings: 75.1%
created: myapp.dmg
hdiutil does not support internet-enable. Note it was removed in macOS 10.15.
Disk image done
```

**Comment by mightybyte** [comment]
Oops, I didn't see the `--no-internet-enable` option at first.  That fixed it for me.  Sorry for the noise.

**Comment by ufukhawk** [comment]
> Oops, I didn't see the `--no-internet-enable` option at first. That fixed it for me. Sorry for the noise.

Where exactly did you add this? i am new to this and i am getting this error  :/
